# Generated by Django 5.0.7 on 2024-08-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_cart_delivery_charge_cart_discount_cart_platform_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='platform_fee',
        ),
    ]
