# Generated by Django 5.0.7 on 2024-08-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
