# Generated by Django 5.0.7 on 2024-08-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_remove_product_seller_dash_items_seller_dash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_dash',
            old_name='user',
            new_name='userr',
        ),
    ]
