# Generated by Django 5.0.7 on 2024-08-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0011_rename_user_seller_dash_userr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_dash',
            name='userr',
        ),
        migrations.DeleteModel(
            name='dash_items',
        ),
        migrations.DeleteModel(
            name='seller_dash',
        ),
    ]
